[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000

[functions]
  included_files = ["dist/client/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"
